### ISSUE TITLE
setup_test_course.php fails

### ISSUE THREAD

**Issue by llt-tuggy** [llttugraz/moodle-lytix_helper#9]
This is because the path to the required `config.php` is wrong. Line 30 needs to be changed to this:

```php
require(__DIR__ . '/../../../../../config.php');
```

**Comment by GerhardU** [comment]
Fixed in  [commit](https://github.com/llttugraz/moodle-lytix_helper/pull/10/commits/87c45a55f59578654b38c71a8f69ea1a41bfb705)
